TesteWeb/TesteWeb/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TesteWeb.Data;
using TesteWeb.Models;
using System.Diagnostics;

namespace TesteWeb.Controllers
{
    public class ProductsController : Controller
    {
        private readonly TesteWebContext _context;

        public ProductsController(TesteWebContext context)
        {
            _context = context;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Product.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Produto,Preço,OBS")] Product product)
        {
            if (ModelState.IsValid)
            {
                _context.Add(product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Success), new { msgSuccess = "Cadastro efetuado com sucesso!" });
            }
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Produto,Preço,OBS")] Product product)
        {
            if (id != product.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Success), new { msgSuccess = "Editado com sucesso!" });
            }
            return View(product);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Product
                .FirstOrDefaultAsync(m => m.Id == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Product.FindAsync(id);
            _context.Product.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Success), new { msgSuccess = "Excluído com sucesso!" });
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.Id == id);
        }
        public IActionResult Success(string msgSuccess)
        {

            var viewModel = new SuccessViewModel
            {
                MsgSuccess = msgSuccess,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };
            return View(viewModel);
        }
    }
}

TesteWeb/TesteWeb/Controllers/SellersController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TesteWeb.Data;
using TesteWeb.Models;

namespace TesteWeb.Controllers
{
    public class SellersController : Controller
    {
        private readonly TesteWebContext _context;

        public SellersController(TesteWebContext context)
        {
            _context = context;
        }

        // GET: Sellers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Seller.ToListAsync());
        }

        // GET: Sellers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seller = await _context.Seller
                .FirstOrDefaultAsync(m => m.Id == id);
            if (seller == null)
            {
                return NotFound();
            }

            return View(seller);
        }

        // GET: Sellers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Sellers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Nome,Email,Telefone")] Seller seller)
        {
            if (ModelState.IsValid)
            {
                _context.Add(seller);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Success), new { msgSuccess = "Cadastro efetuado com sucesso!" });             
            }
            return View(seller);
        }

        // GET: Sellers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seller = await _context.Seller.FindAsync(id);
            if (seller == null)
            {
                return NotFound();
            }
            return View(seller);
        }

        // POST: Sellers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Nome,Email,Telefone")] Seller seller)
        {
            if (id != seller.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(seller);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SellerExists(seller.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Success), new { msgSuccess = "Cadastro editado com sucesso!" });
            }
            return View(seller);
        }

        // GET: Sellers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var seller = await _context.Seller
                .FirstOrDefaultAsync(m => m.Id == id);
            if (seller == null)
            {
                return NotFound();
            }

            return View(seller);
        }

        // POST: Sellers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var seller = await _context.Seller.FindAsync(id);
            _context.Seller.Remove(seller);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Success), new { msgSuccess = "Cadastro excluído com sucesso!" });
        }

        private bool SellerExists(int id)
        {
            return _context.Seller.Any(e => e.Id == id);
        }
        public IActionResult Success(string msgSuccess)
        {

            var viewModel = new SuccessViewModel
            {
                MsgSuccess = msgSuccess,
                RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier
            };
            return View(viewModel);
        }
    }
}

TesteWeb/TesteWeb/Views/Shared/Login.cshtml
@{
    Layout = null; // Layout dashboard não será exibido.
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sir Stakehouse</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="~/lib/bootstrap/dist/css/FormLogin.css" rel="stylesheet" />

</head>

<body>
    <div class="wrapper">
        <br>
        <h3>Login</h3>
        <form action="#">
            <div class="row">
                <i class="fa fa-user"></i>
                <input type="email" placeholder="Informe um e-mail válido..." />
            </div>
            <div class="row">
                <i class="fa fa-key"></i>
                <input type="password" placeholder="Informe uma senha válida..." />
            </div><br>
            <div class="row">
                <input class="btnSubmit btn-info" type="submit" value="Entrar">
            </div>
        </form>
    </div>

    <footer class="footer">
        &copy; 2021 <a asp-controller="Home" asp-action="Login">Sir Stakehouse - Todos os direitos reservados.</a>
    </footer>

    <script src="~/lib/bootstrap/dist/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

TesteWeb/TesteWeb/Views/Shared/Success.cshtml
@model TesteWeb.Models.SuccessViewModel

        <h1 class="text-success">@Model.MsgSuccess</h1>
        
        <!--Temporizador da página após o cadastro e atualiza dinamicamente voltando pra index -->
        <script type="text/javascript">

            (function () {
                setTimeout(function ()
                {
                    window.location = "https://localhost:44311";
                }, 2000); /* 2000ms == 2 segundos*/
            })();

        </script>

TesteWeb/TesteWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!--<title>@ViewData["Title"] - Sir Stakehouse</title>-->

    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>    
    <div class="navigation">
        <ul>
            <li>
                <a asp-controller="Home" asp-action="Index">
                    <span class="icon"> <i class="fa fa-dashboard" aria-hidden="true"></i></span>
                    <span class="title">Dashboard</span>
                </a>
            </li>
            <li>
                <a asp-controller="Products" asp-action="Index">
                    <span class="icon"> <i class="fa fa-list-alt" aria-hidden="true"></i></span>
                    <span class="title">Produtos</span>
                </a>
            </li>
            <li>
                <a asp-controller="Sellers" asp-action="Index">
                    <span class="icon"> <i class="fa fa-users" aria-hidden="true"></i></span>
                    <span class="title">Funcionários</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <span class="icon"> <i class="fa fa-list" aria-hidden="true"></i></span>
                    <span class="title">Pedidos</span>
                </a>
            </li>
            <li>
                <a href="#">
                    <span class="icon"> <i class="fa fa-user-plus" aria-hidden="true"></i></span>
                    <span class="title">Clientes</span>
                </a>
            </li>
            <li>
                <a asp-controller="Home" asp-action="Login">
                    <span class="icon"> <i class="fa fa-power-off" aria-hidden="true"></i></span>
                    <span class="title">Sair</span>
                </a>
            </li>
        </ul>
    </div>
    <div class="toggle" onclick="toggleMenu()"></div> <!--Chamando menu de navegação-->

    <script type="text/javascript">
        function toggleMenu() {
            let toggle = document.querySelector('.navigation');
            toggle.classList.toggle('active');

        }
    </script>

    <div class="container">        
        <main>
            @RenderBody()
        </main>
    </div>

    <footer class="footer">
        &copy; 2021 <a asp-controller="Home" asp-action="Index">Sir Stakehouse - Todos os direitos reservados.</a>
    </footer>

    <script src="~/lib/bootstrap/dist/js/main.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/jquery/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)  <!--Seção de script a ser renderizado-->

</body>
</html>